services:
  postgres:
    container_name: oms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: oms_pg_user
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - oms-net
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: oms_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_oms_user
      - MONGO_INITDB_ROOT_PASSWORD=123456

  mongo-express:
    image: mongo-express:latest
    container_name: oms_mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo_oms_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH=false


  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@ms_kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ms_kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: kafka-cluster-1
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"
    networks:
      - oms-net
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8090"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ms_kafka:9092
    networks:
      - oms-net
    restart: unless-stopped

  mail-dev:
    container_name: oms-mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"



networks:
  oms-net:
    driver: bridge


volumes:
  postgres:
  pgadmin:
  mongo:
  kafka-data: